version: "3.9"

services:

  oracle:
    networks:
      - jiranet
    image: tososomaru/oracle19c:1.0.0
    container_name: oracle19c
    environment:
      - ORACLE_ALLOW_REMOTE=true
      - ORACLE_SID=ORCLCDB
      - ORACLE_PDB=test
      - ORACLE_PWD=admin
    ports:
      - 8080:8080
      - 1521:1521
      - 5500:5500
    volumes:
      - ./oracle:/opt/oracle/scripts/startup
      - oracle-data:/opt/oracle/product
    hostname: oracle
    healthcheck:
      test: sh /opt/oracle/checkDBStatus.sh
      interval: 2m
      start_period: 5m
      timeout: 30s
      retries: 15
  
  jirasoftware:
    networks:
      - jiranet
    depends_on: 
      oracle:
        condition: service_healthy

    build: ./jira
    container_name: jirasoftware
    hostname: jirasoftware
    volumes:
      - jiradata:/var/atlassian/jira
      - jiralogs:/opt/atlassian/jira/logs
    environment:
      - VIRTUAL_HOST=localhost
      - CATALINA_OPTS=-Xms2024m -Xmx2048m -Datlassian.plugins.enable.wait=300
      - ATL_JDBC_URL=jdbc:oracle:thin:@oracle:1521/ORCLCDB
      - ATL_JDBC_USER=jiradbuser
      - ATL_JDBC_PASSWORD=jiradbpassword
      - ATL_DB_DRIVER=oracle.jdbc.OracleDriver
      - ATL_DB_TYPE=oracle10g
      - ATL_DB_SCHEMA_NAME=NONE
    ports:
      - "9080:8080"

volumes:
  jiradata:
    external: false
  jiralogs:
    external: false
  oracle-data:
    external: false

networks:
  jiranet:
    driver: bridge